const { PrismaClient } = require('@prisma/client');

const DATABASE_URL = "postgresql://postgres.swdgtxkeemdrmqaecvhb:q9GhEUAmMOPWzLnN@aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?pgbouncer=true&sslmode=require";

const prisma = new PrismaClient({
  datasources: {
    db: {
      url: DATABASE_URL
    }
  }
});

async function migrateSchema() {
  try {
    console.log('🔄 Migrasi Schema Database...\n');
    
    // Drop tabel lama jika ada
    console.log('🗑️  Dropping tabel lama...');
    
    const dropQueries = [
      'DROP TABLE IF EXISTS public.transaksi CASCADE',
      'DROP TABLE IF EXISTS public.tagihan CASCADE',
      'DROP TABLE IF EXISTS public.krs CASCADE',
      'DROP TABLE IF EXISTS public.pertemuan_kuliah CASCADE',
      'DROP TABLE IF EXISTS public.kelas CASCADE',
      'DROP TABLE IF EXISTS public.kurikulum CASCADE',
      'DROP TABLE IF EXISTS public.dosen CASCADE',
      'DROP TABLE IF EXISTS public.mahasiswa CASCADE',
      'DROP TABLE IF EXISTS public.pendaftar CASCADE',
      'DROP TABLE IF EXISTS public.users CASCADE',
      'DROP TABLE IF EXISTS public.profiles CASCADE',
      'DROP TABLE IF EXISTS public.program_studi CASCADE',
      'DROP TABLE IF EXISTS public.tahun_ajaran CASCADE',
      'DROP TABLE IF EXISTS public.settings CASCADE',
    ];
    
    for (const query of dropQueries) {
      try {
        await prisma.$executeRawUnsafe(query);
      } catch (e) {
        // Ignore errors
      }
    }
    console.log('  ✅ Tabel lama berhasil di-drop\n');
    
    // Buat tabel baru sesuai schema Prisma
    console.log('📝 Membuat tabel baru sesuai schema Prisma...\n');
    
    const createQueries = [
      // Settings
      `CREATE TABLE public.settings (
        id INTEGER PRIMARY KEY DEFAULT 1,
        school_name VARCHAR(255) DEFAULT 'SIAKAD UNIVERSITAS',
        school_logo_url VARCHAR(500) DEFAULT '/Wikimedia-logo.png',
        updated_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT one_row_only CHECK (id = 1)
      )`,
      
      // Tahun Ajaran
      `CREATE TABLE public.tahun_ajaran (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tahun VARCHAR(20) NOT NULL,
        semester VARCHAR(10) NOT NULL,
        is_active BOOLEAN DEFAULT false,
        created_at TIMESTAMPTZ DEFAULT NOW()
      )`,
      
      // Program Studi
      `CREATE TABLE public.program_studi (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nama_prodi VARCHAR(255) NOT NULL,
        kode_prodi VARCHAR(50) UNIQUE NOT NULL,
        fakultas VARCHAR(255),
        created_at TIMESTAMPTZ DEFAULT NOW()
      )`,
      
      // Users
      `CREATE TABLE public.users (
        id UUID PRIMARY KEY,
        email VARCHAR(255) UNIQUE NOT NULL,
        role VARCHAR(20) NOT NULL DEFAULT 'mahasiswa',
        nama_lengkap VARCHAR(255),
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
      )`,
      
      // Pendaftar
      `CREATE TABLE public.pendaftar (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id UUID UNIQUE NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
        nama_lengkap VARCHAR(255) NOT NULL,
        prodi_pilihan BIGINT NOT NULL REFERENCES public.program_studi(id),
        status_seleksi VARCHAR(20) DEFAULT 'pending',
        berkas_url VARCHAR(500),
        created_at TIMESTAMPTZ DEFAULT NOW()
      )`,
      
      // Mahasiswa
      `CREATE TABLE public.mahasiswa (
        id UUID PRIMARY KEY,
        user_id UUID UNIQUE NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
        nim VARCHAR(50) UNIQUE NOT NULL,
        prodi_id BIGINT NOT NULL REFERENCES public.program_studi(id),
        angkatan INTEGER NOT NULL,
        status_aktif BOOLEAN DEFAULT true,
        created_at TIMESTAMPTZ DEFAULT NOW()
      )`,
      
      // Dosen
      `CREATE TABLE public.dosen (
        id UUID PRIMARY KEY,
        user_id UUID UNIQUE NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
        nidn VARCHAR(50) UNIQUE,
        nama_lengkap VARCHAR(255) NOT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW()
      )`,
      
      // Kurikulum
      `CREATE TABLE public.kurikulum (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nama_kurikulum VARCHAR(255) NOT NULL,
        prodi_id BIGINT NOT NULL REFERENCES public.program_studi(id),
        is_active BOOLEAN DEFAULT false,
        created_at TIMESTAMPTZ DEFAULT NOW()
      )`,
      
      // Kelas
      `CREATE TABLE public.kelas (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nama_kelas VARCHAR(255) NOT NULL,
        prodi_id BIGINT NOT NULL REFERENCES public.program_studi(id),
        dosen_id UUID NOT NULL REFERENCES public.dosen(id),
        tahun_ajaran_id BIGINT NOT NULL REFERENCES public.tahun_ajaran(id),
        created_at TIMESTAMPTZ DEFAULT NOW()
      )`,
      
      // Pertemuan Kuliah
      `CREATE TABLE public.pertemuan_kuliah (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        kelas_id BIGINT NOT NULL REFERENCES public.kelas(id) ON DELETE CASCADE,
        jitsi_room_id VARCHAR(255) NOT NULL,
        waktu_mulai TIMESTAMPTZ NOT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW()
      )`,
      
      // KRS
      `CREATE TABLE public.krs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        mahasiswa_id UUID NOT NULL REFERENCES public.mahasiswa(id) ON DELETE CASCADE,
        kelas_id BIGINT NOT NULL REFERENCES public.kelas(id) ON DELETE CASCADE,
        status VARCHAR(50) DEFAULT 'approved',
        created_at TIMESTAMPTZ DEFAULT NOW(),
        UNIQUE(mahasiswa_id, kelas_id)
      )`,
      
      // Tagihan
      `CREATE TABLE public.tagihan (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        mahasiswa_id UUID NOT NULL REFERENCES public.mahasiswa(id) ON DELETE CASCADE,
        nominal DECIMAL(12,2) NOT NULL,
        kategori VARCHAR(100) NOT NULL,
        status VARCHAR(20) DEFAULT 'Unpaid',
        deadline TIMESTAMPTZ,
        created_at TIMESTAMPTZ DEFAULT NOW()
      )`,
      
      // Transaksi
      `CREATE TABLE public.transaksi (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tagihan_id BIGINT NOT NULL REFERENCES public.tagihan(id) ON DELETE CASCADE,
        metode VARCHAR(20) NOT NULL,
        bukti_bayar_url VARCHAR(500),
        verified_by UUID,
        verified_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ DEFAULT NOW()
      )`,
    ];
    
    for (const query of createQueries) {
      try {
        await prisma.$executeRawUnsafe(query);
      } catch (e) {
        if (e.message.includes('already exists')) {
          console.log(`  ⚠️  Tabel sudah ada: ${query.match(/public\.(\w+)/)?.[1]}`);
        } else {
          console.log(`  ❌ Error: ${e.message}`);
        }
      }
    }
    
    console.log('  ✅ Tabel baru berhasil dibuat\n');
    
    // Seed data
    console.log('🌱 Memulai Seeding Database...\n');
    
    // 1. Seed Settings
    console.log('📝 Seeding Settings...');
    await prisma.$executeRawUnsafe(`
      INSERT INTO public.settings (id, school_name, school_logo_url)
      VALUES (1, 'SIAKAD UNIVERSITAS PRISMA', '/Wikimedia-logo.png')
      ON CONFLICT (id) DO UPDATE SET school_name = 'SIAKAD UNIVERSITAS PRISMA'
    `);
    console.log('  ✅ Settings seeded');
    
    // 2. Seed Tahun Ajaran
    console.log('\n📅 Seeding Tahun Ajaran...');
    const tahunAjaranResult = await prisma.$queryRaw`
      INSERT INTO public.tahun_ajaran (tahun, semester, is_active)
      VALUES ('2025/2026', 'Ganjil', true)
      RETURNING id
    `;
    console.log('  ✅ Tahun Ajaran seeded: 2025/2026 Ganjil');
    
    // 3. Seed Program Studi
    console.log('\n📚 Seeding Program Studi...');
    const prodis = [
      { nama: 'Teknik Informatika', kode: 'IF', fakultas: 'Teknik' },
      { nama: 'Sistem Informasi', kode: 'SI', fakultas: 'Teknik' },
      { nama: 'Manajemen', kode: 'MNJ', fakultas: 'Ekonomi & Bisnis' },
      { nama: 'Akuntansi', kode: 'AK', fakultas: 'Ekonomi & Bisnis' },
    ];

    for (const prodi of prodis) {
      await prisma.$executeRawUnsafe(`
        INSERT INTO public.program_studi (nama_prodi, kode_prodi, fakultas)
        VALUES ('${prodi.nama}', '${prodi.kode}', '${prodi.fakultas}')
        ON CONFLICT (kode_prodi) DO NOTHING
      `);
      console.log(`  ✅ ${prodi.nama} (${prodi.kode})`);
    }
    
    console.log('\n✨ Seeding Selesai!\n');
    
    // Tampilkan ringkasan
    console.log('📊 Ringkasan Database:');
    const settingsResult = await prisma.$queryRaw`SELECT COUNT(*) FROM public.settings`;
    const tahunAjaranCount = await prisma.$queryRaw`SELECT COUNT(*) FROM public.tahun_ajaran`;
    const prodiCount = await prisma.$queryRaw`SELECT COUNT(*) FROM public.program_studi`;
    const userCount = await prisma.$queryRaw`SELECT COUNT(*) FROM public.users`;
    const mahasiswaCount = await prisma.$queryRaw`SELECT COUNT(*) FROM public.mahasiswa`;
    const dosenCount = await prisma.$queryRaw`SELECT COUNT(*) FROM public.dosen`;
    const kelasCount = await prisma.$queryRaw`SELECT COUNT(*) FROM public.kelas`;
    
    console.log(`  - Settings: ${settingsResult[0].count} record`);
    console.log(`  - Tahun Ajaran: ${tahunAjaranCount[0].count} record`);
    console.log(`  - Program Studi: ${prodiCount[0].count} records`);
    console.log(`  - User: ${userCount[0].count} records`);
    console.log(`  - Mahasiswa: ${mahasiswaCount[0].count} records`);
    console.log(`  - Dosen: ${dosenCount[0].count} records`);
    console.log(`  - Kelas: ${kelasCount[0].count} records`);
    
    console.log('\n💡 Sekarang buka Prisma Studio dengan: npx prisma studio');
    
  } catch (error) {
    console.error('❌ Error:', error.message);
    if (error.meta) {
      console.error('Meta:', error.meta);
    }
  } finally {
    await prisma.$disconnect();
  }
}

migrateSchema();
