-- =========================================================
-- SETUP FINAL SIAKAD - V2 (STABLE & SECURE)
-- =========================================================

-- 1. BERSIHKAN
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
DROP TABLE IF EXISTS public.program_studi CASCADE;
DROP TABLE IF EXISTS public.mahasiswa CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public.settings CASCADE;
DROP TYPE IF EXISTS user_role CASCADE;

-- 2. TIPE DATA
CREATE TYPE user_role AS ENUM ('admin', 'bendahara', 'dosen', 'mahasiswa');

-- 3. TABEL UTAMA
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  role user_role NOT NULL DEFAULT 'mahasiswa',
  nama_lengkap TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.settings (
  id INTEGER PRIMARY KEY DEFAULT 1,
  school_name TEXT DEFAULT 'SIAKAD UNIVERSITAS',
  school_logo_url TEXT DEFAULT '/Wikimedia-logo.png',
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT one_row_only CHECK (id = 1)
);

INSERT INTO public.settings (id, school_name, school_logo_url)
VALUES (1, 'SIAKAD UNIVERSITAS', '/Wikimedia-logo.png')
ON CONFLICT (id) DO NOTHING;

-- 4. TABEL AKADEMIK
CREATE TABLE public.program_studi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_prodi TEXT NOT NULL,
  kode_prodi TEXT UNIQUE NOT NULL,
  fakultas TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.mahasiswa (
  id UUID REFERENCES public.profiles(id) ON DELETE CASCADE PRIMARY KEY,
  nim TEXT UNIQUE NOT NULL,
  prodi_id BIGINT REFERENCES public.program_studi(id),
  angkatan INTEGER NOT NULL,
  status_aktif BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. TRIGGER PROFIL OTOMATIS
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  is_first_admin BOOLEAN;
BEGIN
  -- Cek apakah ini pendaftar pertama (untuk dijadikan admin)
  SELECT NOT EXISTS (SELECT 1 FROM public.profiles WHERE role = 'admin') INTO is_first_admin;

  INSERT INTO public.profiles (id, email, nama_lengkap, role)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'full_name', ''),
    CASE WHEN is_first_admin THEN 'admin'::user_role ELSE 'mahasiswa'::user_role END
  );
  RETURN new;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 6. KEBIJAKAN KEAMANAN (RLS) - LANGSUNG & STABIL
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.program_studi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mahasiswa ENABLE ROW LEVEL SECURITY;

-- Kebijakan Profil
CREATE POLICY "Profiles: Read all" ON public.profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "Profiles: Update self" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id);
CREATE POLICY "Profiles: Admin manage all" ON public.profiles FOR ALL TO authenticated 
  USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');

-- Kebijakan Settings
CREATE POLICY "Settings: Read all" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Settings: Admin update" ON public.settings FOR UPDATE TO authenticated 
  USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');

-- Kebijakan Program Studi
CREATE POLICY "Prodi: Read all" ON public.program_studi FOR SELECT TO authenticated USING (true);
CREATE POLICY "Prodi: Admin manage" ON public.program_studi FOR ALL TO authenticated 
  USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');

-- Kebijakan Mahasiswa
CREATE POLICY "Mahasiswa: Read all" ON public.mahasiswa FOR SELECT TO authenticated USING (true);
CREATE POLICY "Mahasiswa: Admin manage" ON public.mahasiswa FOR ALL TO authenticated 
  USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');
