-- Create custom types for roles and statuses
CREATE TYPE user_role AS ENUM ('admin', 'bendahara', 'dosen', 'mahasiswa');
CREATE TYPE pendaftaran_status AS ENUM ('pending', 'accepted', 'rejected');
CREATE TYPE tagihan_status AS ENUM ('Unpaid', 'Paid');
CREATE TYPE payment_method AS ENUM ('Otomatis', 'Manual');

-- Profile table (extends auth.users)
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  role user_role NOT NULL DEFAULT 'mahasiswa',
  nama_lengkap TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tahun Ajaran
CREATE TABLE public.tahun_ajaran (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tahun TEXT NOT NULL, -- e.g., "2023/2024"
  semester TEXT NOT NULL, -- e.g., "Ganjil", "Genap"
  is_active BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Program Studi
CREATE TABLE public.program_studi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_prodi TEXT NOT NULL,
  kode_prodi TEXT UNIQUE NOT NULL,
  fakultas TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Dosen
CREATE TABLE public.dosen (
  id UUID REFERENCES public.profiles(id) ON DELETE CASCADE PRIMARY KEY,
  nidn TEXT UNIQUE,
  nama_lengkap TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Mahasiswa
CREATE TABLE public.mahasiswa (
  id UUID REFERENCES public.profiles(id) ON DELETE CASCADE PRIMARY KEY,
  nim TEXT UNIQUE NOT NULL,
  prodi_id BIGINT REFERENCES public.program_studi(id),
  angkatan INTEGER NOT NULL,
  status_aktif BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Pendaftar
CREATE TABLE public.pendaftar (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id),
  nama_lengkap TEXT NOT NULL,
  prodi_pilihan BIGINT REFERENCES public.program_studi(id),
  status_seleksi pendaftaran_status DEFAULT 'pending',
  berkas_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Kurikulum
CREATE TABLE public.kurikulum (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_kurikulum TEXT NOT NULL,
  prodi_id BIGINT REFERENCES public.program_studi(id),
  is_active BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Kelas
CREATE TABLE public.kelas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_kelas TEXT NOT NULL,
  prodi_id BIGINT REFERENCES public.program_studi(id),
  dosen_id UUID REFERENCES public.dosen(id),
  tahun_ajaran_id BIGINT REFERENCES public.tahun_ajaran(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Pertemuan Kuliah (Online with Jitsi)
CREATE TABLE public.pertemuan_kuliah (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kelas_id BIGINT REFERENCES public.kelas(id),
  jitsi_room_id TEXT NOT NULL,
  waktu_mulai TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- KRS (Kartu Rencana Studi)
CREATE TABLE public.krs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mahasiswa_id UUID REFERENCES public.mahasiswa(id),
  kelas_id BIGINT REFERENCES public.kelas(id),
  status TEXT DEFAULT 'approved', -- or pending
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(mahasiswa_id, kelas_id)
);

-- Tagihan
CREATE TABLE public.tagihan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mahasiswa_id UUID REFERENCES public.mahasiswa(id),
  nominal DECIMAL(12,2) NOT NULL,
  kategori TEXT NOT NULL, -- e.g., "UKT", "PMB", "Wisuda"
  status tagihan_status DEFAULT 'Unpaid',
  deadline TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Transaksi
CREATE TABLE public.transaksi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tagihan_id BIGINT REFERENCES public.tagihan(id),
  metode payment_method NOT NULL,
  bukti_bayar_url TEXT,
  verified_by UUID REFERENCES public.profiles(id),
  verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tahun_ajaran ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.program_studi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dosen ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mahasiswa ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pendaftar ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kurikulum ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kelas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pertemuan_kuliah ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.krs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tagihan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transaksi ENABLE ROW LEVEL SECURITY;

-- Basic Policies (example: Admin can do anything)
-- You will need to refine these for each role!
CREATE POLICY "Admins can do everything" ON public.profiles FOR ALL TO authenticated USING (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
);

-- Automated Profile Creation on Signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, nama_lengkap, role)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name', COALESCE((new.raw_user_meta_data->>'role')::user_role, 'mahasiswa'));
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
